name: subscription_manager
description: "サブスクリプションサービスを簡単に解約できるモバイルアプリ"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # HTTP and API
  http: ^1.2.1

  # Local Storage
  shared_preferences: ^2.2.3

  # URL Launcher
  url_launcher: ^6.2.6

  # Date Utilities
  intl: ^0.19.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
